### ISSUE TITLE
Error while completing payment process

### ISSUE THREAD

**Issue by chitrag99** [sanzeeb3/hbl-payment-for-woocommerce#1] opened 2022-12-18 16:09 UTC
2022-12-18T15:10:52+00:00 INFO Generating payment form for order 6726. Notify URL: https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
2022-12-18T15:10:52+00:00 INFO Himalayan Bank Payment Request Args for order 6726: Array
(
    [apiRequest] => Array
        (
            [requestMessageID] => d4100df0-9f4f-2499-94f5-6361fcf23a3e
            [requestDateTime] => 2022-12-18T15:10:52.000Z
            [language] => en-US
        )

    [officeId] => 9103334314
    [orderNo] => 6726
    [productDescription] => product desc.
    [paymentType] => CC
    [paymentCategory] => ECOM
    [storeCardDetails] => Array
        (
            [storeCardFlag] => N
            [storedCardUniqueID] => {{guid}}
        )

    [installmentPaymentDetails] => Array
        (
            [ippFlag] => N
            [installmentPeriod] => 0
            [interestType] => 
        )

    [mcpFlag] => N
    [request3dsFlag] => N
    [transactionAmount] => Array
        (
            [amountText] => 000000030000
            [currencyCode] => USD
            [decimalPlaces] => 2
            [amount] => 300.00
        )

    [notificationURLs] => Array
        (
            [confirmationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [failedURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [cancellationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [backendURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
        )

    [purchaseItems] => Array
        (
            [0] => Array
                (
                    [purchaseItemType] => ticket
                    [referenceNo] => 6726
                    [purchaseItemDescription] => Product Description
                    [purchaseItemPrice] => Array
                        (
                            [amountText] => 000000030000
                            [currencyCode] => USD
                            [decimalPlaces] => 2
                            [amount] => 300.00
                        )

                    [subMerchantID] => string
                    [passengerSeqNo] => 1
                )

        )

)

2022-12-18T15:10:53+00:00 INFO Response details for 6726:

**Comment by sanzeeb3** [comment] 2022-12-19 05:10
Hi @chitrag99 - did you check with the test credentials by enabling test mode?

**Comment by chitrag99** [comment] 2022-12-19 11:50
Hello Sajeeb Ji,

Today I got a call from the bank and he asked you to call Mr. Sujan at this no 9779803560838 so, can you call him and get help? Because they need some keys to need to be generated.

**Comment by sanzeeb3** [comment] 2022-12-19 12:52
Thanks for the update!

**Comment by chitrag99** [comment] 2022-12-20 14:37
Still not working I am not sure.

2022-12-20T14:16:59+00:00 INFO Generating payment form for order 6739. Notify URL: https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
2022-12-20T14:16:59+00:00 INFO Himalayan Bank Payment Request Args for order 6739: Array
(
    [apiRequest] => Array
        (
            [requestMessageID] => 5f176eae-16f0-8cd5-d5ad-8b0491645cef
            [requestDateTime] => 2022-12-20T14:16:59.000Z
            [language] => en-US
        )

    [officeId] => 9103332177
    [orderNo] => 6739
    [productDescription] => product desc.
    [paymentType] => CC
    [paymentCategory] => ECOM
    [storeCardDetails] => Array
        (
            [storeCardFlag] => N
            [storedCardUniqueID] => {{guid}}
        )

    [installmentPaymentDetails] => Array
        (
            [ippFlag] => N
            [installmentPeriod] => 0
            [interestType] => 
        )

    [mcpFlag] => N
    [request3dsFlag] => N
    [transactionAmount] => Array
        (
            [amountText] => 000000030000
            [currencyCode] => USD
            [decimalPlaces] => 2
            [amount] => 300.00
        )

    [notificationURLs] => Array
        (
            [confirmationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [failedURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [cancellationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [backendURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
        )

    [purchaseItems] => Array
        (
            [0] => Array
                (
                    [purchaseItemType] => ticket
                    [referenceNo] => 6739
                    [purchaseItemDescription] => Product Description
                    [purchaseItemPrice] => Array
                        (
                            [amountText] => 000000030000
                            [currencyCode] => USD
                            [decimalPlaces] => 2
                            [amount] => 300.00
                        )

                    [subMerchantID] => string
                    [passengerSeqNo] => 1
                )

        )

)

2022-12-20T14:17:01+00:00 INFO Response details for 6739: stdClass Object
(
    [version] => 1.0
    [apiResponse] => stdClass Object
        (
            [responseMessageId] => d95e518f-5ad3-45fb-90d2-bd73987452b7
            [responseToRequestMessageId] => 0HMMV8DEAFMJA:00000001
            [responseCode] => PC-B050035
            [responseDescription] => No payment routings found that matches payment conditions
            [responseDateTime] => 2022-12-20T14:17:01.3978004Z
            [responseTime] => 550
            [marketingDescription] => No payment routings found that matches payment conditions
        )

)

2022-12-20T14:27:37+00:00 INFO Generating payment form for order 6740. Notify URL: https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
2022-12-20T14:27:37+00:00 INFO Himalayan Bank Payment Request Args for order 6740: Array
(
    [apiRequest] => Array
        (
            [requestMessageID] => 3ba78ad7-059d-25f0-35c5-a847a541ed17
            [requestDateTime] => 2022-12-20T14:27:37.000Z
            [language] => en-US
        )

    [officeId] => 9103334314
    [orderNo] => 6740
    [productDescription] => product desc.
    [paymentType] => CC
    [paymentCategory] => ECOM
    [storeCardDetails] => Array
        (
            [storeCardFlag] => N
            [storedCardUniqueID] => {{guid}}
        )

    [installmentPaymentDetails] => Array
        (
            [ippFlag] => N
            [installmentPeriod] => 0
            [interestType] => 
        )

    [mcpFlag] => N
    [request3dsFlag] => N
    [transactionAmount] => Array
        (
            [amountText] => 000000030000
            [currencyCode] => USD
            [decimalPlaces] => 2
            [amount] => 300.00
        )

    [notificationURLs] => Array
        (
            [confirmationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [failedURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [cancellationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [backendURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
        )

    [purchaseItems] => Array
        (
            [0] => Array
                (
                    [purchaseItemType] => ticket
                    [referenceNo] => 6740
                    [purchaseItemDescription] => Product Description
                    [purchaseItemPrice] => Array
                        (
                            [amountText] => 000000030000
                            [currencyCode] => USD
                            [decimalPlaces] => 2
                            [amount] => 300.00
                        )

                    [subMerchantID] => string
                    [passengerSeqNo] => 1
                )

        )

)

2022-12-20T14:27:38+00:00 INFO Response details for 6740: 
2022-12-20T14:28:46+00:00 INFO Generating payment form for order 6741. Notify URL: https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
2022-12-20T14:28:46+00:00 INFO Himalayan Bank Payment Request Args for order 6741: Array
(
    [apiRequest] => Array
        (
            [requestMessageID] => f09e2aaf-3b4f-c1be-4b6b-df7b6eb7ca8a
            [requestDateTime] => 2022-12-20T14:28:46.000Z
            [language] => en-US
        )

    [officeId] => 9103334314
    [orderNo] => 6741
    [productDescription] => product desc.
    [paymentType] => CC
    [paymentCategory] => ECOM
    [storeCardDetails] => Array
        (
            [storeCardFlag] => N
            [storedCardUniqueID] => {{guid}}
        )

    [installmentPaymentDetails] => Array
        (
            [ippFlag] => N
            [installmentPeriod] => 0
            [interestType] => 
        )

    [mcpFlag] => N
    [request3dsFlag] => N
    [transactionAmount] => Array
        (
            [amountText] => 000000030000
            [currencyCode] => USD
            [decimalPlaces] => 2
            [amount] => 300.00
        )

    [notificationURLs] => Array
        (
            [confirmationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [failedURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [cancellationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [backendURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
        )

    [purchaseItems] => Array
        (
            [0] => Array
                (
                    [purchaseItemType] => ticket
                    [referenceNo] => 6741
                    [purchaseItemDescription] => Product Description
                    [purchaseItemPrice] => Array
                        (
                            [amountText] => 000000030000
                            [currencyCode] => USD
                            [decimalPlaces] => 2
                            [amount] => 300.00
                        )

                    [subMerchantID] => string
                    [passengerSeqNo] => 1
                )

        )

)

2022-12-20T14:28:47+00:00 INFO Response details for 6741:

**Comment by sanzeeb3** [comment] 2022-12-20 14:45
@chitrag99 did you [check with test mode](https://sanjeebaryal.com.np/accept-himalayan-bank-payment-from-your-woocommerce-site#testing) already?

**Comment by chitrag99** [comment] 2022-12-20 16:36
I did but not working

**Comment by sanzeeb3** [comment] 2022-12-20 16:57
> I did but not working

You did? By using DEMOOFFICE office Id? The log is indicating otherwise.

`[officeId] => 9103334314`

**Comment by sanzeeb3** [comment] 2022-12-21 03:03
@chitrag99 - the test mode should work fine. I recommend you test again & report back.

With that said, there's still an issue with live mode with the response:

```
[response] => Array
        (
            [code] => 415
            [message] => Unsupported Media Type
        )
```

which needs to be fixed. I'm looking to fix this issue till next week.  Hope this clarifies.

**Comment by chitrag99** [comment] 2022-12-21 04:55
here is the result after test mode

2022-12-21T04:38:55+00:00 INFO Generating payment form for order 6742. Notify URL: https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
2022-12-21T04:38:55+00:00 INFO Himalayan Bank Payment Request Args for order 6742: Array
(
    [apiRequest] => Array
        (
            [requestMessageID] => c4a4fa7e-65e2-079d-e8ec-141f6eb29600
            [requestDateTime] => 2022-12-21T04:38:55.000Z
            [language] => en-US
        )

    [officeId] => DEMOOFFICE
    [orderNo] => 6742
    [productDescription] => product desc.
    [paymentType] => CC
    [paymentCategory] => ECOM
    [storeCardDetails] => Array
        (
            [storeCardFlag] => N
            [storedCardUniqueID] => {{guid}}
        )

    [installmentPaymentDetails] => Array
        (
            [ippFlag] => N
            [installmentPeriod] => 0
            [interestType] => 
        )

    [mcpFlag] => N
    [request3dsFlag] => N
    [transactionAmount] => Array
        (
            [amountText] => 000000030000
            [currencyCode] => USD
            [decimalPlaces] => 2
            [amount] => 300.00
        )

    [notificationURLs] => Array
        (
            [confirmationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [failedURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [cancellationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [backendURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
        )

    [purchaseItems] => Array
        (
            [0] => Array
                (
                    [purchaseItemType] => ticket
                    [referenceNo] => 6742
                    [purchaseItemDescription] => Product Description
                    [purchaseItemPrice] => Array
                        (
                            [amountText] => 000000030000
                            [currencyCode] => USD
                            [decimalPlaces] => 2
                            [amount] => 300.00
                        )

                    [subMerchantID] => string
                    [passengerSeqNo] => 1
                )

        )

)

2022-12-21T04:38:56+00:00 INFO Response details for 6742: stdClass Object
(
    [version] => 1.0
    [apiResponse] => stdClass Object
        (
            [responseMessageId] => 35200d78-e7be-4aaf-ae80-61fc364ff86c
            [responseToRequestMessageId] => 0HMMV8DEAKF3B:00000001
            [responseCode] => PC-B050005
            [responseDescription] => Invalid amount
            [responseDateTime] => 2022-12-21T04:38:56.5338753Z
            [responseTime] => 411
            [marketingDescription] => Invalid amount
        )

)

2022-12-21T04:48:58+00:00 INFO Generating payment form for order 6744. Notify URL: https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
2022-12-21T04:48:58+00:00 INFO Himalayan Bank Payment Request Args for order 6744: Array
(
    [apiRequest] => Array
        (
            [requestMessageID] => d5a29c2d-e954-a7c4-b4fa-1a9d06847bda
            [requestDateTime] => 2022-12-21T04:48:58.000Z
            [language] => en-US
        )

    [officeId] => DEMOOFFICE
    [orderNo] => 6744
    [productDescription] => product desc.
    [paymentType] => CC
    [paymentCategory] => ECOM
    [storeCardDetails] => Array
        (
            [storeCardFlag] => N
            [storedCardUniqueID] => {{guid}}
        )

    [installmentPaymentDetails] => Array
        (
            [ippFlag] => N
            [installmentPeriod] => 0
            [interestType] => 
        )

    [mcpFlag] => N
    [request3dsFlag] => N
    [transactionAmount] => Array
        (
            [amountText] => 000000000100
            [currencyCode] => USD
            [decimalPlaces] => 2
            [amount] => 1.00
        )

    [notificationURLs] => Array
        (
            [confirmationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [failedURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [cancellationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [backendURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
        )

    [purchaseItems] => Array
        (
            [0] => Array
                (
                    [purchaseItemType] => ticket
                    [referenceNo] => 6744
                    [purchaseItemDescription] => Product Description
                    [purchaseItemPrice] => Array
                        (
                            [amountText] => 000000000100
                            [currencyCode] => USD
                            [decimalPlaces] => 2
                            [amount] => 1.00
                        )

                    [subMerchantID] => string
                    [passengerSeqNo] => 1
                )

        )

)

2022-12-21T04:49:00+00:00 INFO Response details for 6744: stdClass Object
(
    [version] => 1.0
    [apiResponse] => stdClass Object
        (
            [responseMessageId] => 367885b7-2cba-4cf9-a3c6-223b84adc08d
            [responseToRequestMessageId] => 0HMMV8DEAKF4A:00000001
            [responseCode] => PC-B050005
            [responseDescription] => Invalid amount
            [responseDateTime] => 2022-12-21T04:48:59.8914082Z
            [responseTime] => 345
            [marketingDescription] => Invalid amount
        )

)

2022-12-21T04:50:16+00:00 INFO Generating payment form for order 6744. Notify URL: https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
2022-12-21T04:50:16+00:00 INFO Himalayan Bank Payment Request Args for order 6744: Array
(
    [apiRequest] => Array
        (
            [requestMessageID] => e0a4766f-00eb-5649-d802-d32095b98913
            [requestDateTime] => 2022-12-21T04:50:16.000Z
            [language] => en-US
        )

    [officeId] => DEMOOFFICE
    [orderNo] => 6744
    [productDescription] => product desc.
    [paymentType] => CC
    [paymentCategory] => ECOM
    [storeCardDetails] => Array
        (
            [storeCardFlag] => N
            [storedCardUniqueID] => {{guid}}
        )

    [installmentPaymentDetails] => Array
        (
            [ippFlag] => N
            [installmentPeriod] => 0
            [interestType] => 
        )

    [mcpFlag] => N
    [request3dsFlag] => N
    [transactionAmount] => Array
        (
            [amountText] => 000000000100
            [currencyCode] => USD
            [decimalPlaces] => 2
            [amount] => 1.00
        )

    [notificationURLs] => Array
        (
            [confirmationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [failedURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [cancellationURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
            [backendURL] => https://www.egtours.com/wc-api/WC_Gateway_HBL_Payment/
        )

    [purchaseItems] => Array
        (
            [0] => Array
                (
                    [purchaseItemType] => ticket
                    [referenceNo] => 6744
                    [purchaseItemDescription] => Product Description
                    [purchaseItemPrice] => Array
                        (
                            [amountText] => 000000000100
                            [currencyCode] => USD
                            [decimalPlaces] => 2
                            [amount] => 1.00
                        )

                    [subMerchantID] => string
                    [passengerSeqNo] => 1
                )

        )

)

2022-12-21T04:50:17+00:00 INFO Response details for 6744: stdClass Object
(
    [version] => 1.0
    [apiResponse] => stdClass Object
        (
            [responseMessageId] => 8537720e-a8d2-4a53-8502-51d4d484fb21
            [responseToRequestMessageId] => 0HMMV8DEAFP61:00000001
            [responseCode] => PC-B050005
            [responseDescription] => Invalid amount
            [responseDateTime] => 2022-12-21T04:50:17.457955Z
            [responseTime] => 460
            [marketingDescription] => Invalid amount
        )

)

**Comment by chitrag99** [comment] 2022-12-21 04:56
Also, the pop-up form shows only the option of the USA no other countries are listed in the form. Check here

https://ibb.co/bLzSbQ3

**Comment by sanzeeb3** [comment] 2022-12-21 05:03
That's invalid currency. The currency should be Thai Baht for that test merchant as mentioned in the instructions.

The popup form is the behaviour of the browser you're browsing from, the plugin has no control over that.

**Comment by chitrag99** [comment] 2022-12-21 05:57
Hello Sanjeep Ji,

It is successful with test mode when we change the currency to Thai baht. But why not work in real processing?

**Comment by sanzeeb3** [comment] 2022-12-21 06:31
because on the live mode, the response is:

```
[response] => Array
        (
            [code] => 415
            [message] => Unsupported Media Type
        )
        
```
The live API is expecting somethinge else than the test mode.

**Comment by chitrag99** [comment] 2022-12-21 11:16
what is the fix for this? Where should find file to fix?

**Comment by chitrag99** [comment] 2023-01-02 12:28
> @chitrag99 - the test mode should work fine. I recommend you test again & report back.
> 
> With that said, there's still an issue with live mode with the response:
> 
> ```
> [response] => Array
>         (
>             [code] => 415
>             [message] => Unsupported Media Type
>         )
> ```
> 
> which needs to be fixed. I'm looking to fix this issue till next week. Hope this clarifies.

Is this issue going to fix? The plug-in still has issues and not functioning in real-time.

**Comment by sanzeeb3** [comment] 2023-01-02 12:50
The issue is going to be fixed but I have no ETA on the fix.

**Comment by sanzeeb3** [comment] 2023-01-08 02:40
Hi @chitrag99 - the plugin is updated. Please follow the setup instructions in the blog post. If you faced any issues, please report back with the log. 🙏

**Comment by sanzeeb3** [comment] 2023-01-29 03:19
@chitrag99  - closing because the issue is no longer valid.

**Closed by sanzeeb3** 2023-01-29 03:19 UTC
Labels: bug

**Comment by thehiddennepali** [comment] 2023-02-02 09:11
@sanzeeb3 how did you fix the issue of [response] => Array
        (
            [code] => 415
            [message] => Unsupported Media Type
        ), I also faced this issue but didn't get any thing to fix it
